baseurl = "http://www.redox-os.org/"
languageCode = "en-us"
title = "Redox - Your Next(Gen) OS"

[[menu.main]]
  name = "Docs"
  url = "/docs/"
[[menu.main]]
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/redox-os/redox"
[[menu.main]]
  name = "News"
  url = "/news/"
[[menu.main]]
  name = "Screenshots"
  url = "/screens/"
