baseurl = "http://www.redox-os.org/"
languageCode = "en-us"
title = "Redox - Your Next(Gen) OS"

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/redox-os"
[[menu.main]]
  name = "Book"
  url = "/book/book/"
[[menu.main]]
  name = "Docs"
  url = "https://doc.redox-os.org/"
[[menu.main]]
  name = "Forum"
  url = "https://discourse.redox-os.org/"
[[menu.main]]
  name = "Blog"
  url = "/blog/"
[[menu.main]]
  name = "News"
  url = "/news/"
